batch_size: 256
clip_gradient_norm: 1
data_dir: ../../../../data/camels_de
dataset: camels_de
device: cuda:0
dynamic_inputs:
- precipitation_mean
- precipitation_min
- precipitation_max
- humidity_mean
- humidity_min
- humidity_max
- radiation_global_mean
- radiation_global_min
- radiation_global_max
- temperature_mean
- temperature_min
- temperature_max
epochs: 100
experiment_name: single_basin_multi_forcing_hidden_size16_output_dropout0.5_seed321
head: regression
hidden_size: 16
initial_forget_bias: 3
learning_rate: 0.005
log_interval: 4
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: cudalstm
num_layers: 1
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.5
predict_last_n: 1
save_validation_results: true
save_weights_every: 1
seed: 321
seq_length: 365
target_variables:
- discharge_vol
test_basin_file: basin.txt
test_end_date: 31/12/2020
test_start_date: 01/10/2018
train_basin_file: basin.txt
train_end_date: 30/09/2015
train_start_date: 01/01/1951
validate_every: 4
validation_basin_file: basin.txt
validation_end_date: 30/09/2018
validation_start_date: 01/10/2015
